# Generated by Django 3.1.5 on 2021-01-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='created_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='updated_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='created_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='updated_by',
            field=models.JSONField(default=dict),
        ),
    ]
