# Generated by Django 3.1.5 on 2021-01-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
